### ISSUE TITLE
Failure on Intel Xeon CPUs

### ISSUE THREAD

**Issue by arikere** [codeplaysoftware/SYCL-ML#2]
[ctest_log.txt](https://github.com/codeplaysoftware/SYCL-ML/files/2056843/ctest_log.txt)
Attached is the ctest log;
Executing run_svm also fails with the same backtrace shown as in test output.
Also why does it not use all available cpus? Looks like it topped out using only 2 of the ~70 available CPUs. clinfo does see all cpus as sub-devices...

**Comment by Rbiessy** [comment]
Hello,
So it seems the reduction is failing. There are two things you can try:
- Compile with `-DSYCL_PSTL_USE_OLD_ALGO` to use a different kind of algorithm in SyclParallelSTL. Please make sure to clean the build directory (in particular the .sycl files) and you can re-run cmake with `-DCMAKE_CXX_FLAGS="-DSYCL_PSTL_USE_OLD_ALGO" -DCOMPUTECPP_USER_FLAGS="-DSYCL_PSTL_USE_OLD_ALGO"` to add the option for both host and device compiler.
- Check if the reduction sample in [ComputeCpp-sdk](https://github.com/codeplaysoftware/computecpp-sdk) passes. If not there may be an issue with the local barrier.

As for why only 2 CPUs are used, I am not sure. I am wondering whether each CPU is seen as a different device. If that's the case it would be an issue as Eigen and SYCL-ML are built to use only one device for now. It would help if you can paste here the output of computecpp_info.

**Comment by arikere** [comment]
reduction in the samples worked fine. I then recompiled SYCL-ML with the suggested flags and it worked fine.
Looks like the code tops out to 2 cores only initially. Once the PCA step/training starts, it utilizes all available cores.

**Comment by Rbiessy** [comment]
Great, that's good to hear!
I'm closing this issue then, feel free to comment in here or create a new one if you have more issues.
