### ISSUE TITLE
Is the eigen patch needed anymore ?

### ISSUE THREAD

**Issue by zjin-lcf** [codeplaysoftware/SYCL-ML#3]
patching file unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h
Hunk #1 FAILED at 26.
1 out of 1 hunk FAILED -- saving rejects to file unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h.rej
can't find file to patch at input line 16
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

|diff -r d241b80712dc unsupported/Eigen/CXX11/src/Tensor/TensorSyclVirtualPointer.h
|--- a/unsupported/Eigen/CXX11/src/Tensor/TensorSyclVirtualPointer.h    Fri Mar 09 11:31:25 2018 +0000
|+++ b/unsupported/Eigen/CXX11/src/Tensor/TensorSyclVirtualPointer.h    Fri Mar 16 13:36:09 2018 +0000

**Comment by rodburns** [comment]
We are working on getting this project back in sync with Eigen. I'll let you know when we have done that.

**Comment by Rbiessy** [comment]
The project has been updated to work with ComputeCpp 1.2.0. The Eigen patch is not needed anymore, CMake will pull a recent version of Eigen from their new [repository](https://gitlab.com/libeigen/eigen).

I am closing this issue, feel free to create new ones if needed.
