### ISSUE TITLE
raw command

### ISSUE THREAD

**Issue by jinz2014** [codeplaysoftware/SYCL-ML#4]
It is common that users can run 'make' to build examples and tests in your library.  Could you please list the raw command to build an example too ?  This may give users some room for adjusting the compile options. 

Thanks

**Comment by Rbiessy** [comment]
I am not sure what you are asking for. Do you want to see the compiler call by `make`? If so you can either run `VERBOSE=1 make run_lin_classifier` for example (add `-B` if the target was already built to build it again). Alternatively you can enable the verbose output via cmake with `-DCMAKE_VERBOSE_MAKEFILE=ON`.

**Comment by jinz2014** [comment]
Thanks for your instructions.
