### ISSUE TITLE
SVD algorithm

### ISSUE THREAD

**Issue by motorto** [codeplaysoftware/SYCL-ML#5]
What algorithm is the SVD based on ?

Thanks,

**Comment by Rbiessy** [comment]
Hello @motorto,

I have not looked at this project in a long time! I cannot remember and have not left detailed comments on this unfortunately.
All I can find is that this implements a so-called thin SVD. Bear in mind that these operations were not particularly optimized though.

Sorry I cannot be of more help!

**Comment by motorto** [comment]
As of my master thesis I am tasked to implement a SVD for sparse matrix in CSR format in SYCL was just looking to see if the algorithm could take me somewhere.

Do you know any implementation of a parallelized SYCL for sparse matrices, that could help me ?

Appreciate your help.

**Comment by Rbiessy** [comment]
As far as I can tell the algorithm is composed of basic steps that could be implemented for sparse matrices.
As it happens I am working on the sparse domain of [oneMKL Interface](https://github.com/oneapi-src/oneMKL) which aims to provide support for some sparse operations with the SYCL API. Unfortunately for you the project is using other close-source libraries as a backend so it does not implement algorithms in pure SYCL. I am not aware of a project that implements this today.

**Comment by motorto** [comment]
> As far as I can tell the algorithm is composed of basic steps that could be implemented for sparse matrices. As it happens I am working on the sparse domain of [oneMKL Interface](https://github.com/oneapi-src/oneMKL) which aims to provide support for some sparse operations with the SYCL API. Unfortunately for you the project is using other close-source libraries as a backend so it does not implement algorithms in pure SYCL. I am not aware of a project that implements this today.

Well I will try then to implement it from scratch :) 

Any bibliography/algorithm that you could recommend, looking for it to support CSR format. Single-vector Lanczos Recursion ?

**Comment by Rbiessy** [comment]
I am sorry this is well outside of my expertise!

**Comment by motorto** [comment]
No problem. Appreciate your help !
